name: Mergeable

on:
  pull_request:
    branches:
      - master

env:
  container: kali-${{ github.head-ref }}
  tag: ${{ github.sha }}

jobs:
  size:
    runs-on: ubuntu-latest

    steps:
    - name: Deploy the Docker image to GitHub Package Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: artis3n/kali-artis3n/{{ env.container }}
        username: ${{ github.actor }}
        password: ${{ github.token }}
        registry: docker.pkg.github.com
        tags: "${{ env.tag }}"
    
    - name: Keep image size in check
      run: |
        docker pull wagoodman/dive \
        && docker run --rm -t -v /var/run/docker.sock:/var/run/docker.sock wagoodman/dive:latest \
          docker.pkg.github.com/artis3n/kali-artis3n/${{ env.container }}:${{ env.tag}} --ci --ci-config .dive-ci
      env:
        CI: true